### ISSUE TITLE
Long names should be in 'sentence case'/'Title Case' instead of snake_case

### ISSUE THREAD

**Issue by LiamPattinson** [PlasmaFAIR/sdf-xarray#36]
With some extra logic, it could also be possible to add LaTeX formatting for things like "Electric Field $E_x$"

**Comment by JoelLucaAdams** [comment]
Another question that I think should be addressed here is if we want to LaTeX-ify the units as well

**Comment by LiamPattinson** [comment]
I was thinking of just the variables with a subscript of x, y or z, but I suppose there may be a lot more to consider than just those simple cases.

A potential issue with LaTeX-ifying things is that it might just make it harder for users to read `long_name` when they're exploring datasets interactively. LaTeX-ifying units would also likely interfere with the use of units-handling libraries like [xarray-units](https://github.com/astropenguin/xarray-units) or [pint-xarray](https://pint-xarray.readthedocs.io/en/stable/index.html).

Perhaps for now the best option is simply to replace underscores with spaces, and fancy formatting could wait for another issue/PR?

**Comment by JoelLucaAdams** [comment]
@LiamPattinson I think I might have managed to find the solution to the problem in an "elegant" way that doesn't take too much work in the linked PR
