### ISSUE TITLE
Forward slashes in variable names when writing to netcdf

### ISSUE THREAD

**Issue by ZedThree** [PlasmaFAIR/sdf-xarray#6]
```
ValueError: Forward slashes '/' are not allowed in variable and dimension names (got 'Electric Field/Ex'). Forward slashes are used as hierarchy-separators for HDF5-based files ('netcdf4'/'h5netcdf').
```

Either mangle names, or just strip first part off and add to `long_name` attribute?

**Comment by JoelLucaAdams** [comment]
I have a feeling it would be a good idea to mangle the names so it becomes `Electric_Field_Ex` and add it to the `long_name` attribute. I'm pretty sure that's what base EPOCH does anyways so it would be more inline with that and easier for existing `sdf_helper` users when they migrate over.

**Comment by JoelLucaAdams** [comment]
My suggestion would be to convert all spaces and forward slashes in names to be underscores. e.g. Add a helper function to `SDFDataStore`. An example of that change would be as follows:

```python
class SDFDataStore(AbstractDataStore):
# ...
  def load(self):
     # ...
      def _rename_with_underscore(name: str) -> str:
          return name.replace("/", "_").replace(" ", "_")

    # ...
    if isinstance(value, Constant) or value.grid is None:
                data_attrs = {}
                if value.units is not None:
                    data_attrs["units"] = value.units

                # We don't have a grid, either because it's just a
                # scalar, or because it's an array over something
                # else. We have no more information, so just make up
                # some (hopefully) unique dimension names
                shape = getattr(value.data, "shape", ())
                dims = [f"dim_{key}_{n}" for n, _ in enumerate(shape)]
                base_name = _rename_with_underscore(key)

                data_vars[base_name] = Variable(dims, value.data, attrs=data_attrs)
                continue
```

**Comment by ZedThree** [comment]
Yep, that looks reasonable to me. Making all the name valid python identifiers is probably also sensible. Is scheme the same as `sdf_helper`?

Also, we could store the original name as an attribute.

**Comment by JoelLucaAdams** [comment]
This scheme is similar to the one achieved in `sdf_helper` but will have a few key differences. e.g. the `Total_Particle_Energy_in_Simulation__J_` will instead be stored as `Total_Particle_Energy_in_Simulation` on our system and the `J` will be the units. I've attached a small example output from `sdf_helper` below to illustrate this:

Reading file /users/bmp535/scratch/paper/1d_intens_vs_nel_v2/run_0_1000000/run_0_10000/run_0_100/run_0/0000.sdf
t() = time
bx(1024,) = bx
by(1024,) = by
bz(1024,) = bz
ex(1024,) = ex
ey(1024,) = ey
ez(1024,) = ez
jx(1024,) = jx
jy(1024,) = jy
x(1025,) = grid
xc(1024,) = grid_mid
Absorption_Fraction_of_Laser_Energy_Absorbed____ <class 'sdf.BlockConstant'> [1]
Absorption_Total_Laser_Energy_Injected__J_ <class 'sdf.BlockConstant'> [1]
CPUs_Current_rank <class 'sdf.BlockPlainVariable'> [0]
CPUs_Original_rank <class 'sdf.BlockPlainVariable'> [96]
Current_Jx <class 'sdf.BlockPlainVariable'> [1024]
Current_Jy <class 'sdf.BlockPlainVariable'> [1024]
Derived_Average_Particle_Energy <class 'sdf.BlockPlainVariable'> [1024]
Derived_Average_Particle_Energy_Electron <class 'sdf.BlockPlainVariable'> [1024]
Derived_Average_Particle_Energy_Ion <class 'sdf.BlockPlainVariable'> [1024]
Derived_Average_Particle_Energy_Photon <class 'sdf.BlockPlainVariable'> [1024]
Derived_Average_Particle_Energy_Positron <class 'sdf.BlockPlainVariable'> [1024]
Derived_Number_Density <class 'sdf.BlockPlainVariable'> [1024]
Derived_Number_Density_Electron <class 'sdf.BlockPlainVariable'> [1024]
Derived_Number_Density_Ion <class 'sdf.BlockPlainVariable'> [1024]
Derived_Number_Density_Photon <class 'sdf.BlockPlainVariable'> [1024]
Derived_Number_Density_Positron <class 'sdf.BlockPlainVariable'> [1024]
Electric_Field_Ex <class 'sdf.BlockPlainVariable'> [1024]
Electric_Field_Ey <class 'sdf.BlockPlainVariable'> [1024]
Electric_Field_Ez <class 'sdf.BlockPlainVariable'> [1024]
Grid_CPUs_Original_rank <class 'sdf.BlockPlainMesh'> [97]
Grid_CPUs_Original_rank_mid <class 'sdf.BlockPlainMesh'> [96]
Grid_Grid <class 'sdf.BlockPlainMesh'> [1025]
Grid_Grid_mid <class 'sdf.BlockPlainMesh'> [1024]
Magnetic_Field_Bx <class 'sdf.BlockPlainVariable'> [1024]
Magnetic_Field_By <class 'sdf.BlockPlainVariable'> [1024]
Magnetic_Field_Bz <class 'sdf.BlockPlainVariable'> [1024]
Total_Field_Energy_in_Simulation__J_ <class 'sdf.BlockConstant'> [1]
Total_Particle_Energy_Electron__J_ <class 'sdf.BlockConstant'> [1]
Total_Particle_Energy_Ion__J_ <class 'sdf.BlockConstant'> [1]
Total_Particle_Energy_Photon__J_ <class 'sdf.BlockConstant'> [1]
Total_Particle_Energy_Positron__J_ <class 'sdf.BlockConstant'> [1]
Total_Particle_Energy_in_Simulation__J_ <class 'sdf.BlockConstant'> [1]
Wall_time <class 'sdf.BlockConstant'> [1]

**Comment by JoelLucaAdams** [comment]
Another important thing to note is that `sdf_helper` does not remove the starting `Grid_`. I think we should continue to remove it as it's duplication of code

**Comment by JoelLucaAdams** [comment]
If we are going to do this for grid then I see no reason to not do the same for `Particles` as there are 4 variables that start just like that
```python
['Particles_Particles_Per_Cell_Electron', 'Particles_Particles_Per_Cell_Ion', 'Particles_Particles_Per_Cell_Photon', 'Particles_Particles_Per_Cell_Positron']
```

**Comment by ZedThree** [comment]
Yes, good point. It might be sensible to get some other users of EPOCH to weigh in on changing the names, and just do the minimal, sensible thing for now.

I think xarray can now support trees, so it might even be possible to nest variables within groups.
