### ISSUE TITLE
Incorrectly loading sdf data

### ISSUE THREAD

**Issue by JoelLucaAdams** [PlasmaFAIR/sdf-xarray#9]
When I load in the sdf file 0001.sdf I get the following in xarray for the `derived electron number density`: 
![image](https://github.com/user-attachments/assets/03c001bd-3638-4517-bc2a-59c0fce7758d)

Whereas sdf_helper returns:
![image](https://github.com/user-attachments/assets/7cbddfbf-b899-424f-be31-b6c3c192c0f5)

This is unexpected behaviour however at this moment in time I'm unsure how to fix the issue at hand. The setup used to generate this sdf file is hard to replicate so here's a link to it on Google Drive (annoyingly couldn't upload it here) https://drive.google.com/file/d/1LP6vEXk-FFGUHYhgLMUB48PN55hUjNJ4/view?usp=sharing

NOTE: If the file is opened directly using `xr.open_dataset(...)` it works fine but when using the following it fails:
```python
ds = xr.open_mfdataset(
    "/users/bmp535/scratch/epoch_runner/muons_campaign/run_0_1000000/run_0_10000/run_0_100/run_0/*.sdf",
    concat_dim="time",
    combine="nested",
    data_vars='minimal', 
    coords='minimal', 
    compat='override', 
    preprocess=lambda ds: ds.expand_dims(time=[ds.attrs["time"]])
)
```

**Comment by ZedThree** [comment]
I think the issue here is that we should be checking the jobid is consistent across all the files. I'm not sure if this is something that `open_mfdataset` can handle

**Comment by JoelLucaAdams** [comment]
This might be something that could be checked by hooking into the preprocess function. Might need a global variable to store the first id though, I'm imagining something like this? e.g.
```python
from functools import partial
def _preprocess(ds):
    ds = ds.expand_dims(time=[ds.attrs["time"]])
    if job_id is None:
       global job_id = ds.attrs["job_id"]
       return ds

    if (job_id === ds.attrs["job_id"]):
        return ds
    else:
         raise error...

partial_func = partial(_preprocess)
ds = xr.open_mfdataset(
    "file_*.nc", concat_dim="time", preprocess=partial_func
)  
```

**Comment by ZedThree** [comment]
Nice, yes that might work. Make it a functor instead:

```python
class SDFPreprocess:
    def __init__(self):
        self.job_id = None

    def __call__(self, ds):
        ...

ds = xr.open_mfdataset(
    "file_*.nc", concat_dim="time", preprocess=SDFPreprocess()
)  
```

**Comment by JoelLucaAdams** [comment]
I've got this code which seems to do the trick, both erroring correctly and parsing correctly. Not sure if there's a better error to be raised but this does the job just fine:

```python
class SDFPreprocess:
    def __init__(self):
        self.job_id = None

    def __call__(self, ds: xr.Dataset):
        ds = ds.expand_dims(time=[ds.attrs["time"]])
        if self.job_id is None:
            self.job_id = ds.attrs["jobid1"]
            return ds
        elif self.job_id == ds.attrs["jobid1"]:
            return ds
        else:
            raise ValueError("Mismatching job ids")
```

**Comment by JoelLucaAdams** [comment]
Sounds good, I'll also link it to this issue so we understand the origin
